# Funding configuration for GitHub Sponsors
# https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

# github: [pavlenkotm]
# patreon: username
# open_collective: project-name
# ko_fi: username
# custom: ["https://your-site.com"]
